Shopper view stores
sjingoi/B07Group7Project pull request #13
Opened 2023-08-02 01:38 UTC by Zain4Rizvi

Implemented Shopper View Store As Fragment

2023-08-02 02:48 UTC, Zain4Rizvi commented on app/src/main/java/com/example/b07group7project/GetStoreImplementation.java
Don't need to add this file but not sure how to remove individual files from pull request

2023-08-02 02:51 UTC, Zain4Rizvi commented
Look over and make sure it dont override accidentally overwrite anything we need in main

2023-08-02 15:13 UTC, aarondme requested changes

2023-08-02 15:13 UTC, aarondme commented on app/src/main/java/com/example/b07group7project/GetStoreImplementation.java
Replace ArrayList with List (if the method you use this for only requires List)

2023-08-02 15:13 UTC, aarondme commented on app/src/main/java/com/example/b07group7project/GetStoreInterface.java
Same as above, replace with List if that's convenient

2023-08-02 15:13 UTC, aarondme commented on app/src/main/java/com/example/b07group7project/Store.java
This works for now... talk to Seb about how to hook this up with the Image getter class

2023-08-02 15:13 UTC, aarondme commented on app/src/main/java/com/example/b07group7project/StoreRecyclerViewAdapter.java
This is setting the image as if it was stored on the project. It needs to use some image getter, talk to seb. Same kind of idea as what you did for abstracting over the database should be done over the image getter class for now

2023-08-02 15:19 UTC, aarondme commented on app/src/main/java/com/example/b07group7project/StoreRecyclerViewAdapter.java
No need for the abstraction, just use it directly.

2023-08-03 13:57 UTC, aarondme approved these changes

2023-08-03 13:58 UTC, merged