Create order
sjingoi/B07Group7Project pull request #15
Opened 2023-08-04 13:17 UTC by Zain4Rizvi

2023-08-04 13:20 UTC, Zain4Rizvi commented
Implemented the CreateOrder stuff. I also put the shopper view store stuff in its own package to make it easier to navigate through the files. 

Also Im not sure how to pass user to the database so placeOrderInterface and GetCartInterface might need to be changed  abit

2023-08-04 15:37 UTC, aarondme commented on app/src/main/java/com/example/b07group7project/create_order/CheckoutFragment.java
> +        ArrayList<Product> cart = (ArrayList<Product>) cartInterface.getCart("ExampleUser");
If your casting to ArrayList<Product> anyways, force the getCart() interface to return an arraylist. I mentioned generalizing to List if your implementation doesn't care what kind of list you get. Based on the adapter, you should prefer ArrayList

2023-08-04 15:37 UTC, aarondme commented on app/src/main/java/com/example/b07group7project/create_order/CheckoutFragment.java
> +    public String CalculateTotal(ArrayList<Product> Cart){
methods should be lower camel case. So calculateTotal(), same with the argument. "cart" instead of "Cart"

2023-08-04 15:37 UTC, aarondme commented on app/src/main/java/com/example/b07group7project/create_order/CheckoutRecyclerAdapter.java
> +        String QTY = String.valueOf(products.get(position).getQuantity());
no need to abbreviate names. Just say quantity

2023-08-04 15:37 UTC, aarondme commented on app/src/main/java/com/example/b07group7project/create_order/GetCartImplementation.java
> +            Product prod = new Product("FlashLight", 9.99, 5);
For testing, include a few different product types so you can make sure your buttons call the correct item

2023-08-04 21:44 UTC, Zain4Rizvi commented
Fixed Everything To Work Better With Databse, Approve if looks good and lmk any issues

2023-08-04 22:11 UTC, aarondme requested changes
Needs a "checkout" button. Probably should fake screen to get payment details (make it clear that we don't process payment and user should not provide details...)

2023-08-04 22:11 UTC, aarondme commented on app/src/main/java/com/example/b07group7project/create_order/CheckoutFragment.java
> +    public CheckoutFragment() {
unnecessary

2023-08-04 22:11 UTC, aarondme commented on app/src/main/java/com/example/b07group7project/create_order/CheckoutRecyclerAdapter.java
> +        String name = String.valueOf(products.get(position).getItemName());
extract the products.get(position) to a variable, and refer to that.

2023-08-04 22:11 UTC, aarondme commented on app/src/main/java/com/example/b07group7project/create_order/GetCartImplementation.java
> +        ArrayList<Product> ArrayList;
can delete line 34

2023-08-04 22:33 UTC, aarondme commented
> Needs a "checkout" button. Probably should fake screen to get payment details (make it clear that we don't process payment and user should not provide details...)

Button is present, but hardcoding height/width forces it off screen on some devices

2023-08-04 23:48 UTC, aarondme approved these changes

2023-08-05 04:39 UTC, sjingoi approved these changes

2023-08-05 05:18 UTC, merged